  plugins:
    - name: cors
      config:
        origins:
          - https://bizcard.simon-gpt.com
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        headers:
          - Authorization
          - Content-Type
          - X-Client-Info
          - apikey
          - X-Session-Id
          - Referer
          - Origin
          - Cookie
        exposed_headers:
          - Authorization
          - Content-Type
          - X-Client-Info
          - apikey
          - X-Session-Id
        credentials: true
        max_age: 3600
        preflight_continue: false
    - name: request-transformer
      config:
        add:
          headers:
            - X-Forwarded-Proto:https
            - X-Forwarded-Port:443
            - X-Forwarded-Host:supabase.simon-gpt.com
    - name: key-auth
      config:
        key_names:
          - apikey
          - Authorization
        hide_credentials: false
        anonymous: true
        key_in_body: false
        run_on_preflight: false
    - name: acl
      config:
        allow:
          - anonymous
          - authenticated
        hide_groups_header: true
  routes:
    - name: auth-v1-callback
      paths:
        - /auth/callback
      strip_path: false
      preserve_host: true
      plugins:
        - name: cors
          config:
            origins:
              - https://bizcard.simon-gpt.com
            methods:
              - GET
              - OPTIONS
            headers:
              - Authorization
              - Content-Type
              - X-Client-Info
              - apikey
              - X-Session-Id
              - Referer
              - Origin
              - Cookie
            exposed_headers:
              - Authorization
              - Content-Type
              - X-Client-Info
              - apikey
              - X-Session-Id
            credentials: true
            max_age: 3600
            preflight_continue: false
        - name: request-transformer
          config:
            add:
              headers:
                - X-Forwarded-Proto:https
                - X-Forwarded-Port:443
                - X-Forwarded-Host:supabase.simon-gpt.com 