export interface BusinessCard {
  id: string
  name: string
  nameZh?: string
  position: string
  title?: string
  titleZh?: string
  company: string
  companyZh?: string
  email: string
  phone: string
  mobile?: string
  fax?: string
  wechat?: string
  instagram?: string
  linkedin?: string
  website?: string
  address?: string
  addressZh?: string
  department?: string
  departmentZh?: string
  whatsapp?: string
  line?: string
  telegram?: string
  facebook?: string
  twitter?: string
  imageUrl?: string
  rawText?: string
  notes?: string
  dateAdded?: string
} 